services:
  # Orion is the context broker
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -inReqPayloadMaxSize 52428800 -outReqMsgMaxSize 52428800
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  # MongoDB database
  mongo-db:
    image: mongo:5
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command: --nojournal --wiredTigerCacheSizeGB 2
    volumes:
      - mongo-db:/data

  terriamap:
    image: ghcr.io/terriajs/terriamap:latest
    container_name: terriamap
    hostname: terriamap
    ports:
      - "8080:3001"
    volumes:
      - ./terria/config:/app/wwwroot/config
      - ./terria/init:/app/wwwroot/init
      - ./terria/build/TerriaJS/images:/app/wwwroot/build/TerriaJS/images
    restart: unless-stopped

  otp-build:
    image: opentripplanner/opentripplanner:2.8.1
    container_name: otp-build
    volumes:
      - ./otp/data:/var/opentripplanner
    command: >
      --build
      --save
    restart: "no"

  otp:
    image: opentripplanner/opentripplanner:2.8.1
    container_name: opentripplanner
    depends_on:
      - otp-build
    ports:
      - "8081:8080"
    volumes:
      - ./otp/data:/var/opentripplanner
    command: >
      --load
      --serve
    restart: unless-stopped

volumes:
  mongo-db: